### PR TITLE
Main

### PR DESCRIPTION
**Pull request by ethanpyth**
i was added a dbconnection file for the connection to the database

### CODE REVIEW

**Comment by josh-Muleshi** [comment]
merci excellence mais faut commencer a le faire sur une nouvelle branche

**Comment by josh-Muleshi** [comment]
thank you excellence but you have to start doing it on a new branch

**Comment by yveskalume** [comment]
@josh-Muleshi he doesn't need to create another branch since he forks the project.

**Comment by josh-Muleshi** [comment]
ah good ! thank you very much yve i didn't know that

**Comment by josh-Muleshi** [comment]
ah good ! thank you very much @YvesKalume yve i didn't know that

**Pull request merged**
